<a href="https://colab.research.google.com/github/mayaannkkk/100-days-of-Deep-learning/blob/main/Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)


In [ ]:
tokenizer.word_index

{'india': 1,
 'hip': 2,
 'jeetega': 3,
 'ki': 4,
 'jai': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'modi': 14,
 'ji': 15,
 'inquilab': 16,
 'zindabad': 17}

In [ ]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[9, 1],
 [1, 1],
 [2, 2, 10],
 [3, 11, 3, 1],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequence,padding='post')

In [ ]:
sequences

array([[ 9,  1,  0,  0],
       [ 1,  1,  0,  0],
       [ 2,  2, 10,  0],
       [ 3, 11,  3,  1],
       [12, 13,  4,  5],
       [ 6,  6,  0,  0],
       [ 7,  7,  0,  0],
       [ 8,  8,  0,  0],
       [14, 15,  4,  5],
       [16, 17,  0,  0]], dtype=int32)

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import *
model = Sequential([
    Embedding(18,output_dim=2)
])

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[[ 0.00603656,  0.02098319],
        [-0.01129956,  0.03470603],
        [ 0.00542208, -0.0314123 ],
        [ 0.00542208, -0.0314123 ]],

       [[-0.01129956,  0.03470603],
        [-0.01129956,  0.03470603],
        [ 0.00542208, -0.0314123 ],
        [ 0.00542208, -0.0314123 ]],

       [[ 0.00915403,  0.03067314],
        [ 0.00915403,  0.03067314],
        [ 0.04460534,  0.03519536],
        [ 0.00542208, -0.0314123 ]],

       [[ 0.02365876, -0.01512101],
        [ 0.0023893 , -0.00905361],
        [ 0.02365876, -0.01512101],
        [-0.01129956,  0.03470603]],

       [[ 0.0053931 , -0.03933636],
        [-0.04174739,  0.01392659],
        [ 0.023561  , -0.03531205],
        [-0.02883656, -0.04074144]],

       [[ 0.03964439,  0.02607029],
        [ 0.03964439,  0.02607029],
        [ 0.00542208, -0.0314123 ],
        [ 0.00542208, -0.0314123 ]],

       [[-0.03232183, -0.00849383],
        [-0.03232183, -0.00849383],
        [ 0.00542208, -0.0314123 ],
        [ 0.0054

In [ ]:
(X_train,y_train), (X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model1 = Sequential([
    Embedding(
        input_dim=18,
        output_dim=2,
        input_shape=(4,)
    ),
    SimpleRNN(32),
    Dense(1, activation='sigmoid')
])

model1.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ (None, 4, 2)           │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,189 (4.64 KB)

 Trainable params: 1,189 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model1.compile('adam', 'mse')


In [ ]:
embedding_weights = model1.layers[0].get_weights()[0]


In [ ]:
print("\nEmbedding Matrix Shape:")
print(embedding_weights.shape)

print("\nEmbedding Matrix:\n")
print(embedding_weights)


Embedding Matrix Shape:
(18, 2)

Embedding Matrix:

[[-0.04474697 -0.01129469]
 [-0.02257583 -0.04016839]
 [ 0.00938159  0.04597354]
 [-0.02084222 -0.02948352]
 [-0.03081541  0.01067797]
 [-0.04548183 -0.04207585]
 [ 0.02807425 -0.00316733]
 [ 0.00906718 -0.00849416]
 [-0.02157358 -0.00373145]
 [-0.01652565 -0.02399353]
 [ 0.01707152  0.03561557]
 [-0.01569908  0.01873355]
 [-0.01360919  0.04753667]
 [ 0.02479461 -0.02148222]
 [-0.02858328  0.03680163]
 [ 0.00135775 -0.01362752]
 [-0.01697346 -0.03878143]
 [-0.01933508 -0.02760966]]
